
const MenuImages = {
    
  img1:  require('./starterImages/BruschettaClassica.jpg'),
  img2:  require("./starterImages/CalamariFritti.png"),
  img3:  require("./starterImages/Carpaccio.png"),
  img4:  require("./starterImages/CasaMacaroni.png"),
  img5:  require("./starterImages/FocacciaNduja.png"),
  img6:  require("./starterImages/FoccaciaRosmarino.png"),
  img7:  require("./starterImages/FoccaciaMozzarella.png"),
  img8:  require("./starterImages/FormaggiMisti.png"),
  img9:  require("./starterImages/TorrediVerdure.png"),
  img10: require("./starterImages/Tricolore.png"),
  img11: require("./starterImages/ZuchiniFritti.png"),
  img12: require("./starterImages/ZuppadiPomodoro.png"),
  img13: require("./starterImages/oliveMarinate.png"),
  img14: require("./starterImages/Pane allaglio.png"),
  img15: require("./starterImages/Pane allaglio.png"),
  img16: require("./starterImages/Pane allaglio.png"),
  img17: require("./starterImages/Pane allaglio.png"),
  img18: require("./starterImages/Pane allaglio.png"),
  img19: require("./starterImages/Pane allaglio.png"),
  img20: require("./starterImages/Pane allaglio.png"),
  img21: require("./starterImages/Pane allaglio.png"),
  img22: require("./starterImages/Pane allaglio.png"),
  img23: require("./starterImages/Pane allaglio.png"),
  img24: require("./starterImages/Pane allaglio.png"),
  img25: require("./starterImages/Pane allaglio.png"),
  img26: require("./starterImages/Tricolore.png"),
  img27: require("./starterImages/Tricolore.png"),
  img28: require("./starterImages/Tricolore.png"),
  img29: require("./starterImages/Tricolore.png"),
  img30: require("./starterImages/ZuchiniFritti.png"),
  img31: require("./starterImages/ZuchiniFritti.png"),
  img32: require("./starterImages/ZuchiniFritti.png"),
  img33: require("./starterImages/ZuchiniFritti.png"),
  img34: require("./starterImages/ZuchiniFritti.png"),
  img35: require("./starterImages/ZuchiniFritti.png"),
  img36: require("./starterImages/ZuchiniFritti.png"),
  img37: require("./starterImages/ZuchiniFritti.png"),
  img38: require("./starterImages/ZuchiniFritti.png"),
  img39: require("./starterImages/ZuchiniFritti.png"),
  img40: require("./starterImages/ZuchiniFritti.png"),
  img41: require("./starterImages/ZuchiniFritti.png"),
  img42: require("./starterImages/ZuchiniFritti.png"),
  img43: require("./starterImages/ZuchiniFritti.png"),
  img44: require("./starterImages/ZuchiniFritti.png"),
  img45: require("./starterImages/ZuchiniFritti.png"),
  img46: require("./starterImages/ZuchiniFritti.png"),
  img47: require("./starterImages/ZuchiniFritti.png"),
  img48: require("./starterImages/ZuchiniFritti.png"),
  img49: require("./starterImages/ZuchiniFritti.png"),
  img51: require("./starterImages/ZuchiniFritti.png"),
  img52: require("./starterImages/ZuchiniFritti.png"),
  img53: require("./starterImages/ZuchiniFritti.png"),
  img54: require("./starterImages/ZuchiniFritti.png"),
  img55: require("./starterImages/ZuchiniFritti.png"),
  img56: require("./starterImages/ZuchiniFritti.png"),
  img57: require("./starterImages/ZuchiniFritti.png"),
  img58: require("./starterImages/ZuchiniFritti.png"),
  img59: require("./starterImages/ZuchiniFritti.png"),
  img61: require("./starterImages/ZuchiniFritti.png"),
  img62: require("./starterImages/ZuchiniFritti.png"),
};

export default MenuImages;
